blog/urls.py
from django.urls import path
from blog.apps import BlogConfig
from blog.views import BlogListView, BlogDeleteView, BlogCreateView, BlogDetailView, BlogUpdateView
from django.views.decorators.cache import cache_page, never_cache


app_name = BlogConfig.name

urlpatterns = [
    path('blog/', cache_page(10)(BlogListView.as_view()), name='blog_list'),
    path('blog/create/', BlogCreateView.as_view(), name='blog_create'),
    path('blog/<int:pk>/', BlogDetailView.as_view(), name='blog_detail'),
    path('blog/delete/<int:pk>/', BlogDeleteView.as_view(), name='blog_delete'),
    path('blog/update/<int:pk>/', BlogUpdateView.as_view(), name='blog_update'),
]

config/urls.py
from django.contrib import admin
from django.conf.urls.static import static
from django.urls import path, include
from django.conf import settings
from mailing.apps import MailingConfig



app_name = MailingConfig.name

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mailing.urls', namespace='mailing')),
    path('', include('blog.urls', namespace='blog')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from mailing.models import NULLABLE
from datetime import date
from django.db.models import *


class Blog(Model):
    heading = CharField(max_length=255, unique=True, verbose_name='Заголовок')
    content = TextField(verbose_name='Cодержимое статьи')
    image = ImageField(upload_to='blog_images', verbose_name='Изображение', **NULLABLE)
    views_count = IntegerField(max_length=15, default=0, verbose_name='Количество просмотров')
    publicate_date = DateField(default=date.today, verbose_name='Количество просмотров')
    author = ForeignKey("mailing.User", on_delete=CASCADE, verbose_name='Автор', **NULLABLE)

    def __str__(self):
        return self.heading

    class Meta:
        verbose_name = 'Блог'
        verbose_name_plural = 'Блоги'

blog/forms.py
from blog.models import Blog
from mailing.forms import FormStyleMixin
from django import forms


class BlogForm(FormStyleMixin, forms.ModelForm):
    class Meta:
        model = Blog
        exclude = ('publicate_date', 'views_count', 'author')

blog/views.py
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import CreateView, ListView, DetailView, DeleteView, UpdateView
from blog.forms import BlogForm
from blog.models import Blog


class BlogListView(ListView):
    model = Blog
    template_name = 'blog/blog_list.html'
    extra_context = {
        'title': 'Блог'
    }

class BlogDetailView(LoginRequiredMixin, DetailView):
    model = Blog
    form_class = BlogForm
    template_name = 'blog/blog_detail.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form'] = BlogForm(instance=self.object)
        context['title'] = context['object']

        return context

    def get(self, request, *args, **kwargs):
        self.object = self.get_object()
        self.object.views_count +=1
        self.object.save()
        context = self.get_context_data(object=self.object)

        return self.render_to_response(context)

class BlogCreateView(LoginRequiredMixin, CreateView):
    model = Blog
    form_class = BlogForm
    template_name = 'blog/blog_detail_create_save.html'
    success_url = reverse_lazy('blog:blog_list')
    extra_context = {
        'title': 'Создать рассылку'
    }

    def form_valid(self, form):
        blog = form.save()
        blog.user = self.request.user
        blog.author = self.request.user
        blog.save()

        return super().form_valid(form)

class BlogDeleteView(LoginRequiredMixin, DeleteView):
    model = Blog
    success_url = reverse_lazy('blog:blog_list')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = f"Удалить | {context['object']}"

        return context

class BlogUpdateView(LoginRequiredMixin, UpdateView):
    model = Blog
    form_class = BlogForm
    template_name = 'blog/blog_detail_create_save.html'
    success_url = reverse_lazy('blog:blog_list')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = f"Удалить | {context['object']}"

        return context

blog/templates/blog/includes/inc_blog_card.html
{% for object in object_list %}
    <div class="card-deck mb-3 text-left">
        <div class="card mb-4 box-shadow">
            <div class="card-header">
                <h3 class="my-0 font-weight-normal">{{ object.heading }}</h3>
            </div>
            <div class="card-body">
                <div class="row">
                    <div class="col-md-8">
                        <h5 class="card-title pricing-card-title">
                            {% if object.content|length > 1000 %}
                                {{ object.content|slice:":1000" }}...
                            {% else %}
                                {{ object.content }}
                            {% endif %}
                        </h5>
                        <ul class="list-unstyled mt-3 mb-4">
                            <li style="font-size: 18px;">
                                Количество просмотров: {{ object.views_count }}<br>
                                Дата публикации: {{ object.publicate_date }}
                            </li>
                        </ul>
                        <div class="btn-group d-flex" role="group">
                            <a href="{% url 'blog:blog_detail' object.pk %}" class="btn btn-lg btn-primary mr-2" style="margin-bottom: 5px;">Подробнее</a>
                            {% if request.user == object.author or perms.mailing.setting_the_user_status %}
                                <a href="{% url 'blog:blog_update' object.pk %}" class="btn btn-lg btn-primary mr-2" style="margin-bottom: 5px;">Изменить</a>
                                <a href="{% url 'blog:blog_delete' object.pk %}" class="btn btn-lg btn-danger" style="margin-bottom: 5px;">Удалить</a>
                            {% endif %}
                        </div>
                    </div>
                    <div class="col-md-4">
                        <div class="image-container">
                            {% if object.image %}
                                <img src="{{ object.image.url }}" alt="Generic placeholder image" width="200" height="200">
                            {% else %}
                                <img src="data:image/gif;base64,R0lGODlhAQABAIAAAHd3dwAAACH5BAAAAAAALAAAAAABAAEAAAICRAEAOw==" alt="Generic placeholder image" width="200" height="200">
                            {% endif %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endfor %}