blog/urls.py
from django.urls import path
from blog.apps import BlogConfig
from blog.views import BlogListView, BlogDeleteView, BlogCreateView, BlogDetailView, BlogUpdateView
from django.views.decorators.cache import cache_page, never_cache


app_name = BlogConfig.name

urlpatterns = [
    path('blog/', cache_page(10)(BlogListView.as_view()), name='blog_list'),
    path('blog/create/', BlogCreateView.as_view(), name='blog_create'),
    path('blog/<int:pk>/', BlogDetailView.as_view(), name='blog_detail'),
    path('blog/delete/<int:pk>/', BlogDeleteView.as_view(), name='blog_delete'),
    path('blog/update/<int:pk>/', BlogUpdateView.as_view(), name='blog_update'),
]

config/urls.py
from django.contrib import admin
from django.conf.urls.static import static
from django.urls import path, include
from django.conf import settings
from mailing.apps import MailingConfig



app_name = MailingConfig.name

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mailing.urls', namespace='mailing')),
    path('', include('blog.urls', namespace='blog')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mailing/urls.py
from django.contrib.auth.decorators import login_required
from django.urls import path
from mailing.apps import MailingConfig
from mailing.views import IndexView, MailingListView, UserLoginView, UserRegistrationView, UserLogoutView, \
    UserPasswordResetView, UserPasswordResetDoneView, UserPasswordResetConfirmView, UserPasswordResetCompleteView, \
    MailingDetailView, MailingCreateView, MailingDeleteView, MailingUpdateView, ClientListView, ClientCreateView, \
    ClientDeleteView, ClientDetailView, ClientUpdateView, verify_account, UserVerificationView, UserUpdateView, \
    MailingReportView, set_user_status, UserListView


app_name = MailingConfig.name

urlpatterns = [
    path('', IndexView.as_view(), name='home'),
    path('report/', MailingReportView.as_view(), name='mailing_report'),
    path('registration/', UserRegistrationView.as_view(), name='registration'),
    path('verification/', UserVerificationView.as_view(), name='verify'),
    path('verify/<int:user_pk>/', verify_account, name='verify_account'),
    path('profile/<int:pk>/', UserUpdateView.as_view(), name='user_update'),
    path('mailing/', MailingListView.as_view(), name='mailing_list'),
    path('mailing/create', MailingCreateView.as_view(), name='mailing_create'),
    path('mailing/<int:pk>/', MailingDetailView.as_view(), name='mailing_detail'),
    path('mailing/delete/<int:pk>/', MailingDeleteView.as_view(), name='mailing_delete'),
    path('mailing/update/<int:pk>/', MailingUpdateView.as_view(), name='mailing_update'),
    path('clients/', ClientListView.as_view(), name = 'client_list'),
    path('clients/create', ClientCreateView.as_view(), name = 'client_create'),
    path('clients/delete/<int:pk>/', ClientDeleteView.as_view(), name='client_delete'),
    path('clients/update/<int:pk>/', ClientUpdateView.as_view(), name='client_update'),
    path('clients/<int:pk>/', ClientDetailView.as_view(), name='client_detail'),
    path('login/', UserLoginView.as_view(), name='login'),
    path('logout/', UserLogoutView.as_view(), name='logout'),
    path('password/reset/', UserPasswordResetView.as_view(), name='password_reset'),
    path('password/reset/done/', UserPasswordResetDoneView.as_view(), name='password_reset_done'),
    path('password/reset/confirm/<uidb64>/<token>/', UserPasswordResetConfirmView.as_view(),
         name='password_reset_confirm'),
    path('password/reset/complete/', UserPasswordResetCompleteView.as_view(), name='password_reset_complete'),
    path('users_list/', login_required(UserListView.as_view()), name='users_list'),
    path('users/status/<int:pk>/', set_user_status, name='users_status'),
]

mailing/forms.py
from django.contrib.auth.forms import UserCreationForm, PasswordResetForm, AuthenticationForm, SetPasswordForm
from django import forms
from transliterate.utils import _
from mailing.models import User, Mailing, MailingMessage, MailingTrying, Client


class FormStyleMixin:
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'


class UserForm(FormStyleMixin, UserCreationForm):
    class Meta:
        model = User
        fields = ('email', 'phone_number', 'country')

class UserRegistartionForm(FormStyleMixin, UserCreationForm):
    class Meta:
        model = User
        fields = ('email', 'password1', 'password2', 'avatar', 'phone_number', 'country')

class UserAuthenticationForm(FormStyleMixin, AuthenticationForm):
    class Meta:
        model = User
        fields = '__all__'

class UserPasswordResetForm(FormStyleMixin, PasswordResetForm):
    email = forms.EmailField(
        label=_("Email"),
        max_length=255,
        widget=forms.EmailInput(attrs={"autocomplete": "email"}),
    )

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

    class Meta:
        model = User

class UserResetConfirmForm(SetPasswordForm):
    class Meta:
        model = User

class MailingForm(FormStyleMixin, forms.ModelForm):
    class Meta:
        model = Mailing
        exclude = ('author',)

class MailingMessageForm(FormStyleMixin, forms.ModelForm):
    class Meta:
        model = MailingMessage
        exclude = ['id',]

class MailingTryingForm(FormStyleMixin, forms.ModelForm):
    class Meta:
        model = MailingTrying
        fields = '__all__'

class ClientForm(FormStyleMixin, forms.ModelForm):
    class Meta:
        model = Client
        exclude = ('active_flg', 'author')

mailing/views.py
from django.contrib.auth import login
from django.contrib.auth.decorators import permission_required
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.contrib.auth.views import LoginView, LogoutView, PasswordResetView, PasswordResetConfirmView, \
    PasswordResetDoneView, PasswordResetCompleteView
from django.core.mail import send_mail
from django.forms import inlineformset_factory, modelformset_factory, BaseModelFormSet
from django.http import HttpResponseForbidden
from django.shortcuts import redirect, get_object_or_404
from django.urls import reverse_lazy, reverse
from django.conf import settings
from django.views.generic import TemplateView, CreateView, ListView, DetailView, DeleteView, UpdateView
from blog.models import Blog
from mailing.forms import UserAuthenticationForm, UserRegistartionForm, UserPasswordResetForm, UserResetConfirmForm, \
    MailingForm, MailingMessageForm, ClientForm, UserForm
from mailing.models import Mailing, MailingMessage, MailingTrying, Client, User
# from mailing.services import get_cache


class UserListView(PermissionRequiredMixin, ListView):
    model = User
    permission_required = 'mailing.setting_the_user_status'
    template_name = 'mailing/user/user_list.html'

class UserLoginView(LoginView):
    form_class = UserAuthenticationForm
    template_name = 'mailing/user/user_login.html'
    extra_context = {
        'title': 'Авторизация'
    }

    def get_success_url(self):
        return reverse_lazy('mailing:home')

class UserLogoutView(LogoutView):
    next_page = reverse_lazy('mailing:login')

class UserUpdateView(UpdateView):
    model = User
    form_class = UserForm
    template_name = 'mailing/user/user_update_form.html'
    success_url = reverse_lazy('mailing:home')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['user'] = self.request.user
        context['title'] = f'Профиль | {self.object}'

        return context

class UserRegistrationView(CreateView):
    form_class = UserRegistartionForm
    template_name = 'mailing/user/user_registration.html'
    success_url = reverse_lazy('mailing:verify')
    extra_context = {
        'title': 'Регистрация'
    }

    def form_valid(self, form):
        responce = super().form_valid(form)
        user = form.save(commit=False)
        user.is_active = False
        user.save()

        topic = 'Верификация Skychimp'
        message = f'Добрый день, {user.first_name}! Подтвердите свою учетную запись, перейдя по этой ссылке: ' \
                  f'http://37.143.12.161{reverse_lazy("mailing:verify_account", kwargs={"user_pk": user.pk})}.'
        from_email = settings.EMAIL_HOST_USER
        recipients = [user.email]
        send_mail(
            subject=topic,
            message=message,
            from_email=from_email,
            recipient_list=recipients,
            fail_silently=False
        )

        return responce


def verify_account(request, user_pk):
    user = get_object_or_404(User, pk=user_pk)
    user.is_active = True
    user.save()
    login(request, user)
    return redirect(to=reverse('mailing:login'))

class UserVerificationView(TemplateView):
    template_name = 'mailing/user/user_registration_verify.html'
    extra_context = {
        'title': 'Верификация'
    }

class UserPasswordResetView(PasswordResetView):
    form_class = UserPasswordResetForm
    template_name = 'mailing/user/user_password_reset_form.html'
    success_url = reverse_lazy('mailing:password_reset_done')
    email_template_name = 'mailing/user/user_email_reset.html'
    from_email = settings.EMAIL_HOST_USER
    extra_context = {
        'title': 'Восстановление пароля'
    }

class UserPasswordResetDoneView(PasswordResetDoneView):
    template_name = 'mailing/user/user_password_reset_done.html'
    extra_context = {
        'title': 'Письмо отправлено'
    }

class UserPasswordResetConfirmView(PasswordResetConfirmView):
    form_class = UserResetConfirmForm
    template_name = 'mailing/user/user_password_reset_confirm.html'
    success_url = reverse_lazy('mailing:password_reset_complete')
    extra_context = {
        'title': 'Новый пароль'
    }

class UserPasswordResetCompleteView(PasswordResetCompleteView):
    template_name = 'mailing/user/user_password_reset_complete.html'
    extra_context = {
        'title': 'Пароль изменен'
    }

class IndexView(TemplateView):
    template_name = 'mailing/index.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Главная'
        context['total_mailings'] = Mailing.objects.count()
        context['total_active_mailings'] = Mailing.objects.filter(active_flg=True).count()
        context['unique_mailings_clients'] = Mailing.objects.values('client').distinct().count()
        context['three_random_blogs'] = Blog.objects.order_by('?')[:3]
        context['success_mailings'] = MailingTrying.objects.filter(status='success').count()
        context['error_mailings'] = MailingTrying.objects.filter(status='error').count()

        return context

class MailingListView(ListView):
    model = Mailing
    template_name = 'mailing/mailing_list.html'
    # queryset = get_cache(Mailing)
    extra_context = {
        'title': 'Рассылки'
    }

class MailingDetailView(LoginRequiredMixin, DetailView):
    model = Mailing
    form_class = MailingForm
    template_name = 'mailing/mailing_detail.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form'] = MailingForm(instance=self.object)
        context['title'] = context['object']

        MailingMessageFormSet = inlineformset_factory(
            Mailing,
            MailingMessage,
            form=MailingMessageForm,
            extra=0,
            can_delete=False
        )
        if self.request.method == 'POST':
            context['formset'] = MailingMessageFormSet(self.request.POST, instance=self.object)
        else:
            context['formset'] = MailingMessageFormSet(instance=self.object)

        return context


class MailingCreateView(CreateView):
    model = Mailing
    form_class = MailingForm
    template_name = 'mailing/mailing_mailingmessage_formset.html'
    success_url = reverse_lazy('mailing:mailing_list')

    def form_valid(self, form):
        context = self.get_context_data()
        formset = context['formset']
        mailing = form.save()

        if form.is_valid() and formset.is_valid():
            self.object = form.save()
            formset.instance = self.object
            formset.save()
            mailing.author = self.request.user
            mailing.save()

            return redirect(self.get_success_url())

        return self.render_to_response(self.get_context_data(form=form, formset=formset))

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        context_data['title'] = 'Создать рассылку'
        MailingMessageFormSet = inlineformset_factory(
            Mailing,
            MailingMessage,
            form=MailingMessageForm,
            extra=1,
            can_delete=False
        )
        if self.request.method == 'POST':
            context_data['formset'] = MailingMessageFormSet(self.request.POST, instance=self.object)
        else:
            context_data['formset'] = MailingMessageFormSet(instance=self.object)

        return context_data

class MailingDeleteView(LoginRequiredMixin, DeleteView):
    model = Mailing
    success_url = reverse_lazy('mailing:mailing_list')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = f"Удалить | {context['object']}"

        return context

class MailingUpdateView(LoginRequiredMixin, UpdateView):
    model = Mailing
    form_class = MailingForm
    template_name = 'mailing/mailing_mailingmessage_formset.html'
    success_url = reverse_lazy('mailing:mailing_list')

    def get_form(self, form_class=None):
        form = super().get_form(form_class)
        user = self.request.user

        if not user.has_perm('mailing.setting_the_mailing_status'):
            form.fields.pop('active_flg')
        else:
            form.fields = {'active_flg': form.fields['active_flg']}

        return form

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        mailing = self.get_object()
        MailingMessageFormSet = inlineformset_factory(
            Mailing,
            MailingMessage,
            form=MailingMessageForm,
            extra=0,
            can_delete=False
        )
        if self.request.method == 'POST':
            context_data['formset'] = MailingMessageFormSet(self.request.POST, instance=self.object)
        else:
            context_data['formset'] = MailingMessageFormSet(instance=self.object)

        context_data['title'] = f'Изменить | {mailing.name}'

        return context_data

class ClientListView(ListView):
    model = Client
    form_class = ClientForm
    extra_context = {
        'title': 'Клиенты'
    }

class ClientDetailView(UpdateView):
    model = Client
    form_class = ClientForm
    template_name = 'mailing/client_mailing_formset.html'
    success_url = reverse_lazy('mailing:client_list')

    def get_object(self, queryset=None):
        return self.model.objects.get(pk=self.kwargs['pk'])

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        client = self.object

        MailingFormSet = modelformset_factory(
            Mailing,
            form=MailingForm,
            extra=0,
            can_delete=False,
            formset=BaseModelFormSet
        )
        if self.request.POST:
            formset = MailingFormSet(
                self.request.POST,
                prefix='mailing',

mailing/templates/mailing/base.html
{% load static %}

<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    {% if user.is_authenticated %}
        <title> {{ title }} </title>
        <link rel="canonical" href="https://getbootstrap.com/docs/4.0/examples/pricing/">

        <!-- Bootstrap core CSS -->
        <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

        <!-- Custom styles for this template -->
        <link href="{% static 'css/pricing.css' %}" rel="stylesheet">
   </head>

      <body>
        {% include 'mailing/includes/inc_mailing_menu.html' %}

        <div
                class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
        </div>

        <div class="container">
            {% block content %} {% endblock %}
            {% include 'mailing/includes/inc_mailing_footer.html' %}
        </div>


        <!-- Bootstrap core JavaScript
        ================================================== -->
        <!-- Placed at the end of the document so the pages load faster -->
        <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
        <script src="{% static 'js/popper.min.js' %}"></script>
        <script src="{% static 'js/bootstrap.min.js' %}"></script>
        <script src="{% static 'js/holder.min.js' %}"></script>
        <script>
          Holder.addTheme('thumb', {
            bg: '#55595c',
            fg: '#eceeef',
            text: 'Thumbnail'
          });
        </script>
      </body>
    {% else  %}
        <script>
            window.location.href = "{% url 'mailing:login' %}";
        </script>
    {% endif %}
</html>

mailing/templates/mailing/client_confirm_delete.html
{% extends 'mailing/base.html' %}

{% block title %} {{ title }} {% endblock %}


{% block content %}
    <div class="card">
        <div class="card-body">
            <h5 class="card-title">Удаление клиента</h5>
            <p class="card-text">Вы уверены, что хотите удалить клиента?</p>
            <form method="POST">
                {% csrf_token %}
                <input type="submit" class="btn btn-danger" value="Да">
                <a class="btn btn-success" href="{% url 'mailing:client_list' %}" role="button">Назад</a>
            </form>
        </div>
    </div>
{% endblock %}

mailing/templates/mailing/client_detail.html
{% extends 'mailing/base.html' %}

{% block title %} {{ title }} {% endblock %}

{% block content %}
        <form method="POST">
            {% csrf_token %}
            <div class="row">
                <div class="col-md-12">
                    <div class="card shadow">
                        <div class="card-body">
                            <h4 class="card-title">Данные клиента</h4>
                            <hr>
                            {{ form.as_p }}
                        </div>
                    </div>
                </div>

            </div>
            <button type="submit" class="btn btn-primary mt-4"> {% if object %}Сохранить{% else %}Создать{% endif %}</button>
        </form>
{% endblock %}

mailing/templates/mailing/client_list.html
{% extends 'mailing/base.html' %}

{% block title %}{{ title }}{% endblock %}

{% block content %}
    <div style="text-align: center;">
        <a href="{% url 'mailing:client_create' %}" class="btn btn-lg btn-success" style="margin-bottom: 20px;">Создать клиента</a>
    </div>
    <div>
        {% include 'mailing/includes/inc_client_card.html' %}

    </div>
{% endblock %}

mailing/templates/mailing/client_mailing_formset.html
{% extends 'mailing/base.html' %}

{% block title %} {{ title }} {% endblock %}

{% block content %}
    <form method="POST">
        <div class="row">
            <div class="col-md-6">
                <div class="card shadow">
                    <div class="card-body">
                        {% csrf_token %}
                        <h4 class="card-title">Клиент</h4>
                        <hr>
                        {{ form.as_p }}
                    </div>
                </div>
            </div>

            <div class="col-md-6">
                <div class="card shadow">
                    <div class="card-body">
                        <h4 class="card-title">Рассылки</h4>
                        <hr class="my-4">
                        {{ formset.management_form }}
                        {% for form in formset.forms %}
                                <div class="card-body">
                                    {{ form.as_p }}
                                </div>
                                {% if not forloop.last %}
                                    <hr class="my-4">
                                {% endif %}
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>
    </form>
{% endblock %}

mailing/templates/mailing/index.html
{% extends 'mailing/base.html' %}

{% block title %}{{ title }}{% endblock %}

{% block content %}
    <style>
        .statistics {
            display: flex;
            justify-content: center;
            flex-wrap: wrap;
            margin-bottom: 20px;
            padding-bottom: 20px;
        }

        .statistic-item {
            width: calc(33.33% - 20px);
            margin-right: 20px;
            background-color: #f2f2f2;
            padding: 20px;
            text-align: center;
            margin-bottom: 20px;
        }

        .statistic-item:nth-child(3n) {
            margin-right: 0;
        }

        .statistic-value {
            font-size: 24px;
            color: #00cc00;
        }

        .error-value {
            color: #ff0000;
        }

        .blog-list {
            margin-top: 20px;
        }

        .blog-item {
            background-color: #f9f9f9;
            padding: 20px;
            margin-bottom: 20px;
        }

        .section-title {
            font-size: 28px;
            font-weight: bold;
            margin-bottom: 10px;
            color: #333;
        }

        .section-divider {
            border-bottom: 2px solid #ccc;
            margin-bottom: 20px;
        }
    </style>

    <div class="section">
        <h2 class="section-title">Статистика:</h2>
        <div class="statistics">
            <div class="statistic-item">
                <p class="statistic-value">{{ total_mailings }}</p>
                <p>Количество рассылок всего</p>
            </div>
            <div class="statistic-item">
                <p class="statistic-value">{{ total_active_mailings }}</p>
                <p>Количество активных рассылок</p>
            </div>
            <div class="statistic-item">
                <p class="statistic-value">{{ unique_mailings_clients }}</p>
                <p>Количество уникальных клиентов для рассылок</p>
            </div>
            <div class="statistic-item">
                <p class="statistic-value">{{ success_mailings }}</p>
                <p>Количество успешных рассылок</p>
            </div>
            <div class="statistic-item">
                <p class="statistic-value error-value">{{ error_mailings }}</p>
                <p>Количество неудачных рассылок</p>
            </div>
        </div>
        <hr class="section-divider">
    </div>
    <br>
    <div class="section">
        <h2 class="section-title">Популярные статьи:</h2>
        <div class="blog-list">
            {% for blog in three_random_blogs %}
                <div class="blog-item">
                    <h3 style="color: #39aa31;">{{ blog.heading }}</h3>
                    <p>{{ blog.content }}</p>
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}

mailing/templates/mailing/mailing_confirm_delete.html
{% extends 'mailing/base.html' %}

{% block title %}{{ title }}{% endblock %}


{% block content %}
    <div class="card">
        <div class="card-body">
            <h5 class="card-title">Удаление рассылки</h5>
            <p class="card-text">Вы уверены, что хотите удалить рассылку?</p>
            <form method="POST">
                {% csrf_token %}
                <input type="submit" class="btn btn-danger" value="Да">
                <a class="btn btn-success" href="{% url 'mailing:mailing_list' %}" role="button">Назад</a>
            </form>
        </div>
    </div>
{% endblock %}

mailing/templates/mailing/mailing_detail.html
{% extends 'mailing/base.html' %}

{% block title %} {{ title }} {% endblock %}

{% block content %}
        <form>
            <div class="row">
                <div class="col-md-6">
                    <div class="card shadow">
                        <div class="card-body">
                            {% csrf_token %}
                            <h4 class="card-title">Рассылка</h4>
                            <hr>
                            {{ form.as_p }}
                        </div>
                    </div>
                </div>

                <div class="col-md-6">
                    <div class="card shadow">
                        <div class="card-body">
                            <h4 class="card-title">Письмо</h4>
                            <hr>
                            {{ formset.management_form }}
                            {% for form in formset.forms %}
                                    <div class="card-body">
                                        {{ form.as_p }}
                                    </div>
                            {% endfor %}
                        </div>
                    </div>
                </div>
            </div>

        </form>
{% endblock %}

mailing/templates/mailing/mailing_list.html
{% extends 'mailing/base.html' %}

{% block title %}{{ title }}{% endblock %}

{% block content %}
    <div style="text-align: center;">
        <a href="{% url 'mailing:mailing_create' %}" class="btn btn-lg btn-success" style="margin-bottom: 20px;">Создать рассылку</a>
    </div>
    <div>
        {% include 'mailing/includes/inc_mailing_card.html' %}
    </div>
{% endblock %}

mailing/templates/mailing/mailing_mailingmessage_formset.html
{% extends 'mailing/base.html' %}

{% block title %} {{ title }} {% endblock %}

{% block content %}
    <form method="POST">
        <div class="row">
            <div class="col-md-6">
                <div class="card shadow">
                    <div class="card-body">
                        {% csrf_token %}
                        <h4 class="card-title">Рассылка</h4>
                        <hr>
                        {{ form.as_p }}
                    </div>
                </div>
            </div>
            {% if not perms.mailing.setting_the_mailing_status %}
                <div class="col-md-6">
                    <div class="card shadow">
                        <div class="card-body">
                            <h4 class="card-title">Письмо</h4>
                            <hr>
                            {{ formset.management_form }}
                            {% for form in formset.forms %}
                                    <div class="card-body">
                                        {{ form.as_p }}
                                    </div>
                            {% endfor %}
                        </div>
                    </div>
                </div>
            {% endif %}
        </div>
        <button type="submit" class="btn btn-primary mt-4"> {% if object %}Сохранить{% else %}Создать{% endif %}</button>
    </form>
{% endblock %}

mailing/templates/mailing/mailing_trying_report.html
{% extends 'mailing/base.html' %}

{% block title %}{{ title }}{% endblock %}

{% block content %}
    <div>
        {% include 'mailing/includes/inc_mailing_report.html' %}
    </div>
{% endblock %}